### PR TITLE
Prefer descriptive panic over unwrap

### PR DESCRIPTION
**Pull request by hazel-ocean**
See #23

### CODE REVIEW

**Review by LegNeato — CHANGES_REQUESTED** [review]
I think it will be cleaner to just use `expect()`

**Comment by LegNeato** [comment]
Thanks for the PR! 🍻

**Comment by hazel-ocean** [comment]
I was using the current implementation because I wanted whatever `Display` implementation there is for that error to do its thing. Does `expect()` automatically use that the `Display` impl for that type?

**Comment by srijs** [comment]
Another bit that might be nice to have is a custom error message. Currently we'll just wrap the raw env or parse error, which have fairly generic error messages, and it could be helpful to have a more descriptive message in these cases.

**Comment by hazel-ocean** [comment]
Yeah, that would be nice. But at least you get more info than an `expect("Failed to make a new Runtime")`. That might be a separate issue than this PR?

**Comment by LegNeato** [comment]
Expect uses Debug for the underlying error rather than Display I believe:

https://doc.rust-lang.org/book/second-edition/ch09-02-recoverable-errors-with-result.html

**Comment by hazel-ocean** [comment]
Okay, yeah - if you'd prefer that I'll change it.

**Comment by LegNeato** [comment]
Great, thanks! I think we will leave the more in-depth changes for another PR.

**Pull request merged**
